export const SKILL_LIST = [
  { name: 'Acrobacias', attr: 'dex', trainedOnly: false },
  { name: 'Arcanos', attr: 'int', trainedOnly: true },
  { name: 'Artesanía', attr: 'int', trainedOnly: false },
  { name: 'Atletismo', attr: 'str', trainedOnly: false },
  { name: 'Diplomacia', attr: 'cha', trainedOnly: false },
  { name: 'Engaño', attr: 'cha', trainedOnly: false },
  { name: 'Interpretación', attr: 'cha', trainedOnly: false },
  { name: 'Intimidación', attr: 'cha', trainedOnly: false },
  { name: 'Latrocinio', attr: 'dex', trainedOnly: true },
  { name: 'Medicina', attr: 'wis', trainedOnly: false },
  { name: 'Naturaleza', attr: 'wis', trainedOnly: false },
  { name: 'Ocultismo', attr: 'int', trainedOnly: true },
  { name: 'Religión', attr: 'wis', trainedOnly: false },
  { name: 'Sigilo', attr: 'dex', trainedOnly: false },
  { name: 'Sociedad', attr: 'int', trainedOnly: true },
  { name: 'Supervivencia', attr: 'wis', trainedOnly: false },
] as const;

export const CONDITIONS = [
  { name: 'Asustado', description: 'Penalizador a todas las pruebas y CD.' },
  { name: 'Aturdido', description: 'No puedes actuar.' },
  { name: 'Debilitado', description: 'Penalizador a pruebas de Fuerza y daño.' },
  { name: 'Torpe', description: 'Penalizador a CA y pruebas de Destreza.' },
  { name: 'Drenado', description: 'Penalizador a pruebas de Constitución y reducción de HP Max.' },
  { name: 'Enfermo', description: 'Penalizador a todas las pruebas.' },
  { name: 'Estupefacto', description: 'Penalizador a pruebas de Carisma, Inteligencia y Sabiduría.' },
  { name: 'Tumbado', description: 'Penalizador a CA y ataques.' },
  { name: 'Agarrado', description: 'Inmovilizado y penalizador a CA.' },
  { name: 'Restringido', description: 'Inmovilizado, penalizador a CA y no puedes realizar ciertas acciones.' },
  { name: 'Invisible', description: 'Nadie puede verte.' },
  { name: 'Disimulado', description: 'Los enemigos no saben exactamente dónde estás.' },
  { name: 'Oculto', description: 'Es difícil verte.' },
  { name: 'Moribundo', description: 'Estás a punto de morir.' },
  { name: 'Herido', description: 'Has vuelto de la muerte pero estás frágil.' },
  { name: 'Daño persistente', description: 'Recibes daño cada turno.' },
];
